### ISSUE TITLE
Prevent showing agent and user profile in ticket conversation  

### ISSUE THREAD

**Issue by dinhnguyentrunghoa** [miaconsults/mia#117]

**Comment by dinhnguyentrunghoa** [comment]
@BettyGervasini 
We will check if a message includes keywords: fb, phone number, phone, twitter, zalo, ..... To make sure that the user or agent doesn't send their profile through our system.
If we found a message like that, notice the admin.

**Comment by BettyGervasini** [comment]
Please include all kinds of social media such as linked-in, skype, hangout...

**Comment by swomfire** [comment]
Hi @BettyGervasini, do we need to block the message included the social media or send it normally but included a warning to the admin for the violation ?
