### ISSUE TITLE
Notification system

### ISSUE THREAD

**Issue by dinhnguyentrunghoa** [miaconsults/mia#118]

**Comment by dinhnguyentrunghoa** [comment]
@BettyGervasini
Do you think that one user need help on more than 1 ticket at the same time? If yes,  I think we should have a notification system to know which ticket has the new messages

**Comment by BettyGervasini** [comment]
@dinhnguyentrunghoa User can only have one chat at a time for better control and also to avoid long idle time.
If we allow user to have more than 1 ticket, and there could be a situation where 2 tickets are activated at the same time by different agent and user will have difficulty in managing 2 chats at the same time.
So we limit that user can only have 1 chat at anytime.
