### ISSUE TITLE
Closing ticket process 

### ISSUE THREAD

**Issue by dinhnguyentrunghoa** [miaconsults/mia#125]

**Comment by dinhnguyentrunghoa** [comment]
@BettyGervasini 
A closed ticket will be solved or not. So when a ticket complete, I suggest that we show a screen like below to note the last status of a ticket 
![image](https://user-images.githubusercontent.com/16713398/63403007-a85d1b00-c407-11e9-81d4-230664608a4a.png)
This image came from another application. We will change it to only `Solved` and `Unsolved` and a box to input the reason if this ticket is unsolved.

**Comment by BettyGervasini** [comment]
Yes ok to do this.
