### ISSUE TITLE
List all tickets of a user

### ISSUE THREAD

**Issue by longhpzigvy** [miaconsults/mia#51]
Route: `/dashboard`, `/ticket`
API: `GET /tickets`

- The current ticket list is filled with mocking data. Please remove the mocking ones and apply the real one from the API.
- If no data is returned from the API, please display a small message: `No tickets available, click here to create one`
- When a user clicked on an item on the list, it should navigate user to `/ticket/<ticket_id>`

**Comment by DatNT96** [comment]
Right now, the ticketId will have number format such as `github` @longhpzigvy . It is auto increment when insert a new ticket. Let take a look

![Screen Shot 2019-07-02 at 9 35 04 AM](https://user-images.githubusercontent.com/44045075/60478369-b4044f00-9cac-11e9-92d8-aa5ade0df5c9.png)
