### ISSUE TITLE
Implement admin's user api for admin page

### ISSUE THREAD

**Issue by longhpzigvy** [miaconsults/mia#80]
- Blocked https://github.com/miaconsults/mia/issues/79, https://github.com/miaconsults/mia/issues/77
- API Endpoint: `/api/admin/users`
- Route: `/admin/users`
- Apply API for admin tickets page.
- Once the PR is merge, admin should be able to create, update, remove and list all users in this screen

**Comment by swomfire** [comment]
can we close this
